name: Build Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Folder Audit (Debug)
        # This shows us exactly where your files are
        run: ls -R

      - name: Grant Permissions
        run: |
          chmod +x gradlew
          chmod -R +x gradle/wrapper/

      - name: Build Debug APK
        # We use 'assemble' instead of ':app:assembleDebug' to see if it finds ANY module
        run: ./gradlew assembleDebug --stacktrace --info --no-daemon

      - name: Find and Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ChessEngine-App
          path: "**/*.apk"
          if-no-files-found: error
          
