name: Build Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Fresh Gradle Wrapper
        # This fixes the "corrupt jarfile" error by getting a new one
        run: |
          wget https://services.gradle.org/distributions/gradle-8.2-bin.zip
          unzip gradle-8.2-bin.zip
          cp gradle-8.2/lib/plugins/gradle-wrapper-8.2.jar gradle/wrapper/gradle-wrapper.jar

      - name: Fix Permissions
        run: |
          chmod +x gradlew
          chmod -R +x gradle/wrapper/

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --info --stacktrace --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ChessEngine-App-APK
          path: "**/build/outputs/apk/debug/*.apk"
          if-no-files-found: error
